global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'app'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8000']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
